Repository rauc/rauc-hawkbit-updater, pull requests merged in 2020-04, with the labels that each got.

#22 src/hawkbit-updater: add GError handling for get_available_space
  src/hawkbit-client.c
Labels: bug, enhancement

#20 Gateway token support
  README.md
  config.conf.example
  include/config-file.h
  src/config-file.c
  src/hawkbit-client.c
  test/rauc-hawkbit-updater.t
  test/test-config-auth-token-only.conf
  test/test-config-both-security-tokens.conf
  test/test-config-gateway-token-only.conf
  test/test-config-no-security-tokens.conf
Labels: enhancement

#30 README.md: proper syntax highlighting for config file
  README.md
Labels: documentation

#28 rauc-hawkbit-updater: Fix strptime() and header usage
  include/hawkbit-client.h
  src/hawkbit-client.c
Labels: bug

#27 Fix Error Handling in config-file.c
  src/config-file.c
Labels: bug

#29 src/hawkbit-client: Rework GError handling of get_binary()
  src/hawkbit-client.c
Labels: bug, enhancement
