Repository rauc/rauc-hawkbit-updater, pull requests merged in 2021-03, with the labels that each got.

#77 hawkbit client: refactoring and bug fixes
  include/hawkbit-client.h
  src/hawkbit-client.c
  test/rauc-hawkbit-updater.t
Labels: bugfix, refactoring

#79 Make critical messages fatal, add useful compiler warnings
  CMakeLists.txt
  src/rauc-hawkbit-updater.c
Labels: testing

#74 Starting point for sphinx-based user documentation
  .github/workflows/tests.yml
  CHANGES
  CMakeLists.txt
  README.md
  docs/Makefile
  docs/changes.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/media/rauc-hawkbit-scheme.svg
  docs/media/rauc-hawkbit-updater-scheme.png
  docs/reference.rst
  docs/using.rst
Labels: documentation, testing

#81 Add matrix and documentation badges
  README.md
Labels: documentation
