Repository rauc/rauc-hawkbit-updater, pull requests merged in 2021-01, with the labels that each got.

#69 Move to GitHub actions for testing
  .github/workflows/tests.yml
  .travis.yml
  CMakeLists.txt
Labels: testing

#64 sd-helper: minor refactoring
  include/sd-helper.h
  src/sd-helper.c
Labels: documentation, refactoring

#65 config-file: documentation, refactoring and bug fixes
  include/config-file.h
  include/hawkbit-client.h
  src/config-file.c
  src/hawkbit-client.c
  src/rauc-hawkbit-updater.c
  test/rauc-hawkbit-updater.t
Labels: bugfix, documentation, refactoring

#66 rauc-installer: refactoring and bug fixes
  include/rauc-installer.h
  src/rauc-installer.c
Labels: bugfix, documentation, refactoring

#67 log: update/move doc strings
  include/log.h
  src/log.c
Labels: documentation

#70 .github: tests: use secrets for docker login only for master builds
  .github/workflows/tests.yml
Labels: bugfix, testing

#72 README: use GitHub Actions badge instead of TravisCI
  README.md
Labels: documentation, testing
