Repository rauc/rauc-hawkbit-updater, pull requests merged in 2021-02, with the labels that each got.

#75 .github: tests: run apt-get update before install
  .github/workflows/tests.yml
Labels: bugfix, testing

#68 hawkbit-client: various simplifications
  include/hawkbit-client.h
  src/hawkbit-client.c
Labels: refactoring

#71 rauc-hawkbit-updater: refactoring
  src/rauc-hawkbit-updater.c
Labels: refactoring

#76 test: create_test_target: enable target security token authentication via MGMT API
  test/create_test_target
Labels: testing

#39 Add a reboot option
  README.md
  config.conf.example
  include/config-file.h
  script/rauc-hawkbit-updater.service
  src/config-file.c
  src/hawkbit-client.c
  test/test-config-auth-token-only.conf
  test/test-config-both-security-tokens.conf
  test/test-config-gateway-token-only.conf
  test/test-config-no-security-tokens.conf
  test/test-config.conf
Labels: enhancement
