Repository rauc/rauc-hawkbit-updater, pull requests merged in 2022-10, with the labels that each got.

#113 Replace CMake by meson
  .github/workflows/tests.yml
  CMakeLists.txt
  Doxyfile.in
  README.md
  docs/meson.build
  docs/release-checklist.txt
  meson.build
  meson_options.txt
Labels: build system

#130 Add HTTP Streaming Support
  .github/workflows/tests.yml
  README.md
  docs/reference.rst
  docs/using.rst
  include/config-file.h
  include/hawkbit-client.h
  include/rauc-installer.h
  src/config-file.c
  src/hawkbit-client.c
  src/rauc-hawkbit-updater.c
  src/rauc-installer.c
  test/conftest.py
  test/rauc_dbus_dummy.py
  test/test_basics.py
  test/test_cancel.py
  test/test_install.py
Labels: enhancement

#146 docs: reference: improve stream_bundle documentation
  docs/reference.rst
Labels: documentation

#148 github: bump action versions to fix deprecation warnings
  .github/workflows/tests.yml
Labels: testing
